---
- name: Install commonly used editors, long process (~5mins) 1/2
  apt:
    pkg:
    - dictionaries-common
    - gedit
    - leafpad

- name: Install commonly used editors, long process (~5mins) 2/2
  apt:
    pkg:
    - vim-gtk
    - emacs

- name: add environment variables to .profile
  lineinfile:
    dest: /home/{{ username }}/.profile
    line: "export EDITOR=leafpad"
