#### Install the LXDE desktop
- name: Install packages
  apt:
    pkg:
    - lxde
    - xinput

# Install x2go virtual desktop server
- block:
    - name: Install software-properties-common
      apt:
        name: software-properties-common

    - name: add x2go to apt repo
      apt_repository:
        repo: ppa:x2go/stable
        update_cache: yes

    - name: install x2goserver
      apt:
        pkg:
        - x2goserver
        - x2goserver-xsession
  when: not local

- name: Remove extra packages
  apt:
    state: absent
    autoremove: yes
    pkg:
    - gnome-screensaver
    - lxlock
    - light-locker
    - network-manager-gnome
    - gnome-online-accounts


- name: Install language pack
  apt:
    name: language-pack-en


- name: set language
  command: update-locale LANG=en_GB.utf8

- name: Set UK keyboard
  command: perl -pi -e 's/XKBLAYOUT="us"/XKBLAYOUT="gb"/;' /etc/default/keyboard


# Create a desktop shortcut
- name: Create a desktop shortcut
  file:
    path: /home/{{ username }}/Desktop
    state: directory
    owner: "{{ username }}"

- name: Add terminal shortcut to desktop
  copy:
    src: /usr/share/applications/lxterminal.desktop
    dest: /home/{{ username }}/Desktop
    remote_src: yes
    owner: "{{ username }}"

- name: Enable autologin (1/2)
  copy:
    src: lxdeconf
    dest: /usr/share/lightdm/lightdm.conf.d/lxde.conf

# need to populate username string here
- name: Enable autologin (2/2)
  lineinfile:
    dest: /usr/share/lightdm/lightdm.conf.d/lxde.conf
    line: "{{ item }}"
  with_items:
    - autologin-user={{ username }}
    - autologin-user-timeout=0

# Docs shortcut
- command: dos2unix -n /home/{{ username }}/metomi-vms/home/Desktop/docs.desktop /home/{{ username }}/Desktop/docs.desktop

# Open terminal on startup
- block:
    - name: create autostart dir
      file:
        path: /home/{{ username }}/.config/autostart
        state: directory

    - name: Configure middle button emulation
      copy:
        src: xinput
        dest: /home/{{ username }}/.config/autostart/xinput.desktop

    - name: Copy terminal shortcut to autostart folder
      copy:
        src: /usr/share/applications/lxterminal.desktop
        dest: /home/{{ username }}/.config/autostart
        remote_src: yes

    - name: configure startup terminal
      file:
        path: /home/{{ username }}/.config/clipit
        state: directory

    - name: Copy clipitrc config file
      copy:
        src: clipitrc
        dest: /home/{{ username }}/.config/clipit/clipitrc
  become: yes
  become_user: "{{ username }}"

# Setup desktop background colour
- block:
    - name: create LXDE directory
      file:
        path: /home/{{ username }}/.config/pcmanfm/LXDE
        state: directory
    - name: Copy LXDE config file
      copy:
        src: lxdedeskconf
        dest: /home/{{ username }}/.config/pcmanfm/LXDE/desktop-items-0.conf
  become: yes
  become_user: "{{ username }}"
